# Generated by Django 3.2 on 2022-12-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.AlterField(
            model_name='review',
            name='store_name',
            field=models.CharField(max_length=225, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, verbose_name='コメント詳細'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, verbose_name='コメント'),
        ),
    ]
